### ISSUE TITLE
Package path ./dist/tokenStore/upstash is not exported from package

### ISSUE THREAD

**Issue by anthony-healthstreet** [proofgeist/fmdapi#80]
Version this became an issue - 3.2.15

Error
![image](https://github.com/proofgeist/fmdapi/assets/96539866/d293f099-2c09-4948-a6e6-ad28e9f586ba)

If I modify the package.json 
![image](https://github.com/proofgeist/fmdapi/assets/96539866/98cb6b02-f662-4aaa-92e0-1119183515f5)
 from `./dist/tokenStore/*.js` to `./dist/tokenStore/*`, this error goes away

**Comment by eluce2** [comment]
Would it work for you if you import from "@proofgeist/fmdapi/dist/tokenStore/upstash.js" instead? Including the .js file extension?

**Comment by anthony-healthstreet** [comment]
Potentially another export issue? Also starting at 3.2.15

Running our codegen script, I get this:

```yarn run v1.22.19
$ doppler run -- ts-node --project ./scripts/tsconfig.json ./scripts/codegen && npx prettier ./types/fmschema/ -w
Error: No "exports" main defined in /Users/USERNAME/Documents/repos/REPO_NAME/node_modules/@proofgeist/fmdapi/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:302:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:592:13)
    at resolveExports (node:internal/modules/cjs/loader:596:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:673:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1135:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/USERNAME/Documents/repos/REPO_NAME/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/USERNAME/Documents/repos/REPO_NAME/scripts/util/ApiCall.types.ts:2:1) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 *  The terminal process "/bin/zsh '-l', '-c', 'yarn run schemagen'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. ```

`import { DataApi } from '@proofgeist/fmdapi';` is the only import line in that file. Downgraded temporarily from 3.3.7 to 3.2.0 and it runs.
